/*
CutMeShort CMS API

Official API for the CutMeShort CMS platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package main

import (
	"encoding/json"
	"time"
)

// LeadPayload struct for recording a lead event
type LeadPayload struct {
	// Required for standard lead tracking and for deferred association setup
	ClickId *string `json:"clickId,omitempty"`
	// Name of the lead event
	EventName string `json:"eventName"`
	// Your unique external identifier for the customer
	CustomerExternalId string `json:"customerExternalId"`
	// ISO 8601 timestamp
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Customer's name
	CustomerName *string `json:"customerName,omitempty"`
	// Customer's email
	CustomerEmail *string `json:"customerEmail,omitempty"`
	// Customer's avatar URL
	CustomerAvatar *string `json:"customerAvatar,omitempty"`
	// Use 'deferred' only when creating the deferred clickId-to-customerExternalId association
	Mode *string `json:"mode,omitempty"`
}

// NewLeadPayload instantiates a new LeadPayload object
func NewLeadPayload(eventName string, customerExternalId string) *LeadPayload {
	this := LeadPayload{}
	this.EventName = eventName
	this.CustomerExternalId = customerExternalId
	return &this
}

// NewLeadPayloadWithDefaults instantiates a new LeadPayload object
func NewLeadPayloadWithDefaults() *LeadPayload {
	this := LeadPayload{}
	return &this
}

// GetClickId returns the ClickId field value if set, zero value otherwise
func (o *LeadPayload) GetClickId() string {
	if o == nil || IsNil(o.ClickId) {
		var ret string
		return ret
	}
	return *o.ClickId
}

// GetClickIdOk returns a tuple with the ClickId field value if set, nil otherwise
func (o *LeadPayload) GetClickIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClickId) {
		return nil, false
	}
	return o.ClickId, true
}

// HasClickId returns a boolean if a field has been set
func (o *LeadPayload) HasClickId() bool {
	if o != nil && !IsNil(o.ClickId) {
		return true
	}
	return false
}

// SetClickId sets the ClickId field value
func (o *LeadPayload) SetClickId(v string) {
	o.ClickId = &v
}

// GetEventName returns the EventName field value
func (o *LeadPayload) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value and a boolean to check if the value has been set
func (o *LeadPayload) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets the EventName field value
func (o *LeadPayload) SetEventName(v string) {
	o.EventName = v
}

// GetCustomerExternalId returns the CustomerExternalId field value
func (o *LeadPayload) GetCustomerExternalId() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.CustomerExternalId
}

// GetCustomerExternalIdOk returns a tuple with the CustomerExternalId field value and a boolean to check if the value has been set
func (o *LeadPayload) GetCustomerExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerExternalId, true
}

// SetCustomerExternalId sets the CustomerExternalId field value
func (o *LeadPayload) SetCustomerExternalId(v string) {
	o.CustomerExternalId = v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise
func (o *LeadPayload) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
func (o *LeadPayload) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set
func (o *LeadPayload) HasCustomerName() bool {
	if o != nil && !IsNil(o.CustomerName) {
		return true
	}
	return false
}

// SetCustomerName sets the CustomerName field value
func (o *LeadPayload) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise
func (o *LeadPayload) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail) {
		var ret string
		return ret
	}
	return *o.CustomerEmail
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
func (o *LeadPayload) GetCustomerEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerEmail) {
		return nil, false
	}
	return o.CustomerEmail, true
}

// HasCustomerEmail returns a boolean if a field has been set
func (o *LeadPayload) HasCustomerEmail() bool {
	if o != nil && !IsNil(o.CustomerEmail) {
		return true
	}
	return false
}

// SetCustomerEmail sets the CustomerEmail field value
func (o *LeadPayload) SetCustomerEmail(v string) {
	o.CustomerEmail = &v
}

// GetCustomerAvatar returns the CustomerAvatar field value if set, zero value otherwise
func (o *LeadPayload) GetCustomerAvatar() string {
	if o == nil || IsNil(o.CustomerAvatar) {
		var ret string
		return ret
	}
	return *o.CustomerAvatar
}

// GetCustomerAvatarOk returns a tuple with the CustomerAvatar field value if set, nil otherwise
func (o *LeadPayload) GetCustomerAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerAvatar) {
		return nil, false
	}
	return o.CustomerAvatar, true
}

// HasCustomerAvatar returns a boolean if a field has been set
func (o *LeadPayload) HasCustomerAvatar() bool {
	if o != nil && !IsNil(o.CustomerAvatar) {
		return true
	}
	return false
}

// SetCustomerAvatar sets the CustomerAvatar field value
func (o *LeadPayload) SetCustomerAvatar(v string) {
	o.CustomerAvatar = &v
}

// GetMode returns the Mode field value if set, zero value otherwise
func (o *LeadPayload) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
func (o *LeadPayload) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set
func (o *LeadPayload) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}
	return false
}

// SetMode sets the Mode field value
func (o *LeadPayload) SetMode(v string) {
	o.Mode = &v
}

// MarshalJSON marshals the LeadPayload to JSON
func (o LeadPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClickId) {
		toSerialize["clickId"] = o.ClickId
	}
	if true {
		toSerialize["eventName"] = o.EventName
	}
	if true {
		toSerialize["customerExternalId"] = o.CustomerExternalId
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.CustomerName) {
		toSerialize["customerName"] = o.CustomerName
	}
	if !IsNil(o.CustomerEmail) {
		toSerialize["customerEmail"] = o.CustomerEmail
	}
	if !IsNil(o.CustomerAvatar) {
		toSerialize["customerAvatar"] = o.CustomerAvatar
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	return json.Marshal(toSerialize)
}
