/*
CutMeShort CMS API

Official API for the CutMeShort CMS platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package main

import (
	"encoding/json"
)

// ErrorResponse struct for error responses
type ErrorResponse struct {
	// Error code
	Code *string `json:"code,omitempty"`
	// Error message
	Message string `json:"message"`
	// Request ID for tracing
	RequestId *string `json:"requestId,omitempty"`
	// Additional error details
	Details map[string]interface{} `json:"details,omitempty"`
}

// NewErrorResponse instantiates a new ErrorResponse object
func NewErrorResponse(message string) *ErrorResponse {
	this := ErrorResponse{}
	this.Message = message
	return &this
}

// NewErrorResponseWithDefaults instantiates a new ErrorResponse object with default values
func NewErrorResponseWithDefaults() *ErrorResponse {
	this := ErrorResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise
func (o *ErrorResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
func (o *ErrorResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// SetCode sets the Code field value
func (o *ErrorResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value
func (o *ErrorResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.Message
}

// GetMessageOk returns a tuple with the Message field value and a boolean to check if the value has been set
func (o *ErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets the Message field value
func (o *ErrorResponse) SetMessage(v string) {
	o.Message = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise
func (o *ErrorResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
func (o *ErrorResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// SetRequestId sets the RequestId field value
func (o *ErrorResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// MarshalJSON marshals the ErrorResponse to JSON
func (o ErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if o.Details != nil {
		toSerialize["details"] = o.Details
	}
	return json.Marshal(toSerialize)
}

// UnmarshalJSON unmarshals the ErrorResponse from JSON
func (o *ErrorResponse) UnmarshalJSON(data []byte) error {
	type ErrorResponseTmp struct {
		Code      *string                `json:"code,omitempty"`
		Message   *string                `json:"message,omitempty"`
		RequestId *string                `json:"requestId,omitempty"`
		Details   map[string]interface{} `json:"details,omitempty"`
	}

	var tmp ErrorResponseTmp
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}

	if tmp.Code != nil {
		o.Code = tmp.Code
	}
	if tmp.Message != nil {
		o.Message = *tmp.Message
	}
	if tmp.RequestId != nil {
		o.RequestId = tmp.RequestId
	}
	if tmp.Details != nil {
		o.Details = tmp.Details
	}

	return nil
}
