/*
CutMeShort CMS API

Official API for the CutMeShort CMS platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package main

import (
	"encoding/json"
)

// TrackResponse struct for the API response
type TrackResponse struct {
	// Success message
	Message string `json:"message,omitempty"`
	// Request ID for tracking
	RequestId *string `json:"requestId,omitempty"`
	// Deferred association mode stored successfully
	DeferredAssociationStored *bool `json:"deferredAssociationStored,omitempty"`
}

// NewTrackResponse instantiates a new TrackResponse object
func NewTrackResponse() *TrackResponse {
	this := TrackResponse{}
	return &this
}

// NewTrackResponseWithDefaults instantiates a new TrackResponse object with default values
func NewTrackResponseWithDefaults() *TrackResponse {
	this := TrackResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise
func (o *TrackResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
func (o *TrackResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets the Message field value
func (o *TrackResponse) SetMessage(v string) {
	o.Message = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise
func (o *TrackResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
func (o *TrackResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// SetRequestId sets the RequestId field value
func (o *TrackResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetDeferredAssociationStored returns the DeferredAssociationStored field value if set, zero value otherwise
func (o *TrackResponse) GetDeferredAssociationStored() bool {
	if o == nil || IsNil(o.DeferredAssociationStored) {
		var ret bool
		return ret
	}
	return *o.DeferredAssociationStored
}

// GetDeferredAssociationStoredOk returns a tuple with the DeferredAssociationStored field value if set, nil otherwise
func (o *TrackResponse) GetDeferredAssociationStoredOk() (*bool, bool) {
	if o == nil || IsNil(o.DeferredAssociationStored) {
		return nil, false
	}
	return o.DeferredAssociationStored, true
}

// SetDeferredAssociationStored sets the DeferredAssociationStored field value
func (o *TrackResponse) SetDeferredAssociationStored(v bool) {
	o.DeferredAssociationStored = &v
}

// MarshalJSON marshals the TrackResponse to JSON
func (o TrackResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != "" {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.DeferredAssociationStored) {
		toSerialize["deferredAssociationStored"] = o.DeferredAssociationStored
	}
	return json.Marshal(toSerialize)
}

// UnmarshalJSON unmarshals the TrackResponse from JSON
func (o *TrackResponse) UnmarshalJSON(data []byte) error {
	type TrackResponseTmp struct {
		Message                  *string `json:"message,omitempty"`
		RequestId                *string `json:"requestId,omitempty"`
		DeferredAssociationStored *bool   `json:"deferredAssociationStored,omitempty"`
	}

	var tmp TrackResponseTmp
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}

	if tmp.Message != nil {
		o.Message = *tmp.Message
	}
	if tmp.RequestId != nil {
		o.RequestId = tmp.RequestId
	}
	if tmp.DeferredAssociationStored != nil {
		o.DeferredAssociationStored = tmp.DeferredAssociationStored
	}

	return nil
}
