/*
CutMeShort CMS API

Official API for the CutMeShort CMS platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package main

import (
	"encoding/json"
	"time"
)

// SalePayload struct for recording a sale event
type SalePayload struct {
	// Click ID that initiated the sale
	ClickId string `json:"clickId"`
	// Name of the sale event
	EventName string `json:"eventName"`
	// ISO 8601 timestamp
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Your unique external identifier for the customer
	CustomerExternalId string `json:"customerExternalId"`
	// Customer's name
	CustomerName *string `json:"customerName,omitempty"`
	// Customer's email
	CustomerEmail *string `json:"customerEmail,omitempty"`
	// Customer's avatar URL
	CustomerAvatar *string `json:"customerAvatar,omitempty"`
	// Invoice ID for the sale
	InvoiceId string `json:"invoiceId"`
	// Amount in cents
	Amount float64 `json:"amount"`
	// 3-letter currency code
	Currency string `json:"currency"`
}

// NewSalePayload instantiates a new SalePayload object
func NewSalePayload(clickId string, eventName string, customerExternalId string, invoiceId string, amount float64, currency string) *SalePayload {
	this := SalePayload{}
	this.ClickId = clickId
	this.EventName = eventName
	this.CustomerExternalId = customerExternalId
	this.InvoiceId = invoiceId
	this.Amount = amount
	this.Currency = currency
	return &this
}

// NewSalePayloadWithDefaults instantiates a new SalePayload object
func NewSalePayloadWithDefaults() *SalePayload {
	this := SalePayload{}
	return &this
}

// GetClickId returns the ClickId field value
func (o *SalePayload) GetClickId() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.ClickId
}

// GetClickIdOk returns a tuple with the ClickId field value and a boolean to check if the value has been set
func (o *SalePayload) GetClickIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClickId, true
}

// SetClickId sets the ClickId field value
func (o *SalePayload) SetClickId(v string) {
	o.ClickId = v
}

// GetEventName returns the EventName field value
func (o *SalePayload) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value and a boolean to check if the value has been set
func (o *SalePayload) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets the EventName field value
func (o *SalePayload) SetEventName(v string) {
	o.EventName = v
}

// GetCustomerExternalId returns the CustomerExternalId field value
func (o *SalePayload) GetCustomerExternalId() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.CustomerExternalId
}

// GetCustomerExternalIdOk returns a tuple with the CustomerExternalId field value and a boolean to check if the value has been set
func (o *SalePayload) GetCustomerExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerExternalId, true
}

// SetCustomerExternalId sets the CustomerExternalId field value
func (o *SalePayload) SetCustomerExternalId(v string) {
	o.CustomerExternalId = v
}

// GetInvoiceId returns the InvoiceId field value
func (o *SalePayload) GetInvoiceId() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value and a boolean to check if the value has been set
func (o *SalePayload) GetInvoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceId, true
}

// SetInvoiceId sets the InvoiceId field value
func (o *SalePayload) SetInvoiceId(v string) {
	o.InvoiceId = v
}

// GetAmount returns the Amount field value
func (o *SalePayload) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}
	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value and a boolean to check if the value has been set
func (o *SalePayload) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets the Amount field value
func (o *SalePayload) SetAmount(v float64) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *SalePayload) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value and a boolean to check if the value has been set
func (o *SalePayload) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets the Currency field value
func (o *SalePayload) SetCurrency(v string) {
	o.Currency = v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise
func (o *SalePayload) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
func (o *SalePayload) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// SetCustomerName sets the CustomerName field value
func (o *SalePayload) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise
func (o *SalePayload) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail) {
		var ret string
		return ret
	}
	return *o.CustomerEmail
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
func (o *SalePayload) GetCustomerEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerEmail) {
		return nil, false
	}
	return o.CustomerEmail, true
}

// SetCustomerEmail sets the CustomerEmail field value
func (o *SalePayload) SetCustomerEmail(v string) {
	o.CustomerEmail = &v
}

// GetCustomerAvatar returns the CustomerAvatar field value if set, zero value otherwise
func (o *SalePayload) GetCustomerAvatar() string {
	if o == nil || IsNil(o.CustomerAvatar) {
		var ret string
		return ret
	}
	return *o.CustomerAvatar
}

// GetCustomerAvatarOk returns a tuple with the CustomerAvatar field value if set, nil otherwise
func (o *SalePayload) GetCustomerAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerAvatar) {
		return nil, false
	}
	return o.CustomerAvatar, true
}

// SetCustomerAvatar sets the CustomerAvatar field value
func (o *SalePayload) SetCustomerAvatar(v string) {
	o.CustomerAvatar = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise
func (o *SalePayload) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
func (o *SalePayload) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// SetTimestamp sets the Timestamp field value
func (o *SalePayload) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// MarshalJSON marshals the SalePayload to JSON
func (o SalePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["clickId"] = o.ClickId
	}
	if true {
		toSerialize["eventName"] = o.EventName
	}
	if true {
		toSerialize["customerExternalId"] = o.CustomerExternalId
	}
	if true {
		toSerialize["invoiceId"] = o.InvoiceId
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.CustomerName) {
		toSerialize["customerName"] = o.CustomerName
	}
	if !IsNil(o.CustomerEmail) {
		toSerialize["customerEmail"] = o.CustomerEmail
	}
	if !IsNil(o.CustomerAvatar) {
		toSerialize["customerAvatar"] = o.CustomerAvatar
	}
	return json.Marshal(toSerialize)
}
