/*
CutMeShort CMS API

Official API for the CutMeShort CMS platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package sdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

// TrackingAPIService TrackingAPI service
type TrackingAPIService service

type ApiTrackLeadRequest struct {
	ctx         context.Context
	ApiService  *TrackingAPIService
	leadPayload *LeadPayload
}

func (r ApiTrackLeadRequest) LeadPayload(leadPayload LeadPayload) ApiTrackLeadRequest {
	r.leadPayload = &leadPayload
	return r
}

func (r ApiTrackLeadRequest) Execute() (*TrackResponse, *http.Response, error) {
	return r.ApiService.TrackLeadExecute(r)
}

/*
TrackLead Track a lead event

Records a lead event.

Standard mode:
- Send `clickId`, `eventName`, and `customerExternalId`.

Deferred attribution mode:
- First call: send `clickId`, `eventName`, `customerExternalId`, and `mode: deferred` to store the click association.
- Later calls: send the same `customerExternalId` without `clickId` or `mode` to use the stored association.
*/
func (a *TrackingAPIService) TrackLead(ctx context.Context) ApiTrackLeadRequest {
	return ApiTrackLeadRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// TrackLeadExecute executes the request
func (a *TrackingAPIService) TrackLeadExecute(r ApiTrackLeadRequest) (*TrackResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TrackResponse
	)

	localBasePath := a.client.cfg.Servers.String()
	localVarPath := localBasePath + "/track/lead"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHeaderParams["Content-Type"] = "application/json"
	localVarHeaderParams["Accept"] = "application/json"

	// body params
	localVarPostBody = r.leadPayload

	req, err := http.NewRequestWithContext(ctx, localVarHTTPMethod, localVarPath, bytes.NewBuffer([]byte("")))
	if err != nil {
		return localVarReturnValue, nil, err
	}

	// add headers for context
	for key, value := range localVarHeaderParams {
		req.Header.Add(key, value)
	}

	q := req.URL.Query()
	for _, v := range localVarQueryParams {
		q.Add(v[0], v[1])
	}
	req.URL.RawQuery = q.Encode()

	if r.leadPayload != nil {
		b, err := marshalJSON(*r.leadPayload)
		if err != nil {
			return localVarReturnValue, nil, err
		}
		req.Body = io.NopCloser(bytes.NewBuffer(b))
		req.ContentLength = int64(len(b))
	}

	localVarHTTPResponse, err := a.client.cfg.HTTPClient.Do(req)
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := NewAPIResponse(localVarHTTPResponse)
		newErr.Message = string(localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = unmarshalJSON(localVarBody, &localVarReturnValue)
	if err != nil {
		newErr := NewAPIResponse(localVarHTTPResponse)
		newErr.Message = err.Error()
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiTrackSaleRequest struct {
	ctx        context.Context
	ApiService *TrackingAPIService
	salePayload *SalePayload
}

func (r ApiTrackSaleRequest) SalePayload(salePayload SalePayload) ApiTrackSaleRequest {
	r.salePayload = &salePayload
	return r
}

func (r ApiTrackSaleRequest) Execute() (*TrackResponse, *http.Response, error) {
	return r.ApiService.TrackSaleExecute(r)
}

/*
TrackSale Track a sale event

Records a sale event including transaction details.
*/
func (a *TrackingAPIService) TrackSale(ctx context.Context) ApiTrackSaleRequest {
	return ApiTrackSaleRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// TrackSaleExecute executes the request
func (a *TrackingAPIService) TrackSaleExecute(r ApiTrackSaleRequest) (*TrackResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		localVarReturnValue *TrackResponse
	)

	localBasePath := a.client.cfg.Servers.String()
	localVarPath := localBasePath + "/track/sale"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	localVarHeaderParams["Content-Type"] = "application/json"
	localVarHeaderParams["Accept"] = "application/json"

	// body params
	localVarPostBody = r.salePayload

	req, err := http.NewRequestWithContext(context.Background(), localVarHTTPMethod, localVarPath, bytes.NewBuffer([]byte("")))
	if err != nil {
		return localVarReturnValue, nil, err
	}

	// add headers for context
	for key, value := range localVarHeaderParams {
		req.Header.Add(key, value)
	}

	q := req.URL.Query()
	for _, v := range localVarQueryParams {
		q.Add(v[0], v[1])
	}
	req.URL.RawQuery = q.Encode()

	if r.salePayload != nil {
		b, err := marshalJSON(*r.salePayload)
		if err != nil {
			return localVarReturnValue, nil, err
		}
		req.Body = io.NopCloser(bytes.NewBuffer(b))
		req.ContentLength = int64(len(b))
	}

	localVarHTTPResponse, err := a.client.cfg.HTTPClient.Do(req)
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := NewAPIResponse(localVarHTTPResponse)
		newErr.Message = string(localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = unmarshalJSON(localVarBody, &localVarReturnValue)
	if err != nil {
		newErr := NewAPIResponse(localVarHTTPResponse)
		newErr.Message = err.Error()
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
