/*
CutMeShort CMS API

Official API for the CutMeShort CMS platform. This API allows tracking of leads and sales, including deferred lead attribution.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package sdk

import (
	"net/http"
)

// Configuration stores the configuration of the API client
type Configuration struct {
	Host      string            `json:"host,omitempty"`
	Scheme    string            `json:"scheme,omitempty"`
	DefaultHeader map[string]string `json:"defaultHeader,omitempty"`
	UserAgent string            `json:"userAgent,omitempty"`
	Debug     bool              `json:"debug,omitempty"`
	Servers   ServerConfigurations
	OperationServers map[string]ServerConfigurations
	HTTPClient *http.Client
}

// NewConfiguration returns a new Configuration object
func NewConfiguration() *Configuration {
	cfg := &Configuration{
		DefaultHeader: make(map[string]string),
		UserAgent:     "OpenAPI-Generator/1.0.0/go",
		Servers: ServerConfigurations{
			{
				URL:         "https://www.cutmeshort.com",
				Description: "CutMeShort API Server",
			},
		},
		OperationServers: make(map[string]ServerConfigurations),
		HTTPClient: &http.Client{},
	}
	return cfg
}

// ServerConfiguration stores a server configuration
type ServerConfiguration struct {
	URL         string
	Description string
	Variables   map[string]ServerVariable
}

// ServerVariable stores a server variable
type ServerVariable struct {
	Description      string
	DefaultValue     string
	EnumValues       []string
}

type ServerConfigurations []ServerConfiguration

// URLs returns ServerConfiguration.URL deduplicated over all provided configurations
func (sc ServerConfigurations) URLs() []string {
	urls := []string{}
	for _, serv := range sc {
		urls = append(urls, serv.URL)
	}
	return urls
}

// String returns the first ServerConfiguration.URL
func (sc ServerConfigurations) String() string {
	return sc[0].URL
}

// APIClient manages communication with the CutMeShort CMS API
type APIClient struct {
	cfg    *Configuration
	common service

	// API Services
	TrackingAPI *TrackingAPIService
}

type service struct {
	client *APIClient
}

// NewAPIClient creates and returns a new API client
func NewAPIClient(cfg *Configuration) *APIClient {
	if cfg == nil {
		cfg = NewConfiguration()
	}

	c := &APIClient{}
	c.cfg = cfg
	c.common.client = c

	c.TrackingAPI = (*TrackingAPIService)(&c.common)

	return c
}
