/*
CutMeShort CMS API

Official API for the CutMeShort CMS platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package sdk

import (
	"net/http"
)

// APIResponse stores the API response returned by the server
type APIResponse struct {
	*http.Response `json:"-"`
	Message        string `json:"message,omitempty"`
	// Operation is the name of the OpenAPI operation
	Operation string `json:"operation,omitempty"`
	// RequestURL is the request URL
	RequestURL string `json:"url,omitempty"`
	// Method is the HTTP method used for the request
	Method string `json:"method,omitempty"`
	// Payload holds the contents of the response body
	Payload []byte `json:"-"`
}

// NewAPIResponse returns a new APIResponse object
func NewAPIResponse(r *http.Response) *APIResponse {
	response := &APIResponse{Response: r}
	return response
}

// NewAPIResponseWithError returns a new APIResponse object with the provided error message
func NewAPIResponseWithError(errorMessage string) *APIResponse {
	response := &APIResponse{Message: errorMessage}
	return response
}

// Error implements the error interface
func (r *APIResponse) Error() string {
	return r.Message
}
