/*
CutMeShort CMS API

Official API for the CutMeShort CMS platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// IsNil checks if an interface is nil
func IsNil(i interface{}) bool {
	return i == nil
}

// PtrBool returns a pointer to the given bool value
func PtrBool(v bool) *bool { return &v }

// PtrInt returns a pointer to the given int value
func PtrInt(v int) *int { return &v }

// PtrInt32 returns a pointer to the given int32 value
func PtrInt32(v int32) *int32 { return &v }

// PtrInt64 returns a pointer to the given int64 value
func PtrInt64(v int64) *int64 { return &v }

// PtrFloat32 returns a pointer to the given float32 value
func PtrFloat32(v float32) *float32 { return &v }

// PtrFloat64 returns a pointer to the given float64 value
func PtrFloat64(v float64) *float64 { return &v }

// PtrString returns a pointer to the given string value
func PtrString(v string) *string { return &v }

// marshalJSON marshals a value to JSON
func marshalJSON(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

// unmarshalJSON unmarshals JSON data into a value
func unmarshalJSON(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

// formatBool formats a bool value
func formatBool(v bool) string {
	return fmt.Sprintf("%v", v)
}

// MappedNullable interface for checking nullable fields
type MappedNullable interface {
	ToMap() (map[string]interface{}, error)
}
